const actionTypes = {
    // Products
    PRODUCTOS_REQUEST: 'PRODUCTOS_REQUEST',
    PRODUCTOS: 'PRODUCTOS',
    PRODUCTOS_ID_REQUEST: 'PRODUCTOS_ID_REQUEST',
    PRODUCTOS_ID: 'PRODUCTOS_ID',
    PRODUCTOS_UNICO_REQUEST: 'PRODUCTOS_UNICO_REQUEST',
    PRODUCTOS_UNICO: 'PRODUCTOS_UNICO',

    // cart

    ADD_TO_CART: 'ADD_TO_CART',
    EMPTY_CART: 'EMPTY_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART'
}

export default actionTypes